// <auto-generated />
namespace DVDRentalStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TablePerHierarchy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablePerHierarchy));
        
        string IMigrationMetadata.Id
        {
            get { return "202005141840305_TablePerHierarchy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
